# Generated by Django 3.2.5 on 2022-03-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.EmailField(max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
                ('nickname', models.CharField(default='', max_length=16)),
                ('avatar', models.FileField(default='avatar/default.webp', upload_to='avatar')),
            ],
        ),
    ]
