# Generated by Django 3.2.5 on 2022-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
