# Generated by Django 3.2.5 on 2022-03-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetail',
            name='handle_video',
            field=models.FileField(default='', upload_to='handleVideo'),
        ),
    ]
